#ifndef VKZLIB_MPL_PREPROCESSOR_SIGNATURE_IS_TAG_HPP
#define VKZLIB_MPL_PREPROCESSOR_SIGNATURE_IS_TAG_HPP

#include <vkzlib/mpl/preprocessor/cat.hpp>
#include <vkzlib/mpl/preprocessor/const.hpp>
#include <vkzlib/mpl/preprocessor/pick_second_or.hpp>

// Those macro evaluate to `1` if `X` is desired tag, otherwise `0`

#define _VKZLIB_PP_SIGNATURE_IS_NONE_IMPL_TRUE_None VKZLIB_PP_CONST(1)
#define VKZLIB_PP_SIGNATURE_IS_NONE(X) \
	VKZLIB_PP_PICK_SECOND_OR(0, VKZLIB_PP_CAT(_VKZLIB_PP_SIGNATURE_IS_NONE_IMPL_TRUE_, X))

#define _VKZLIB_PP_SIGNATURE_IS_VARIADIC_IMPL_TRUE_Variadic VKZLIB_PP_CONST(1)
#define VKZLIB_PP_SIGNATURE_IS_VARIADIC(X) \
	VKZLIB_PP_PICK_SECOND_OR(0, VKZLIB_PP_CAT(_VKZLIB_PP_SIGNATURE_IS_VARIADIC_IMPL_TRUE_, X))

#define _VKZLIB_PP_SIGNATURE_IS_CONST_IMPL_TRUE_Const VKZLIB_PP_CONST(1)
#define VKZLIB_PP_SIGNATURE_IS_CONST(X) \
	VKZLIB_PP_PICK_SECOND_OR(0, VKZLIB_PP_CAT(_VKZLIB_PP_SIGNATURE_IS_CONST_IMPL_TRUE_, X))
#define _VKZLIB_PP_SIGNATURE_IS_VOLATILE_IMPL_TRUE_Volatile VKZLIB_PP_CONST(1)
#define VKZLIB_PP_SIGNATURE_IS_VOLATILE(X) \
	VKZLIB_PP_PICK_SECOND_OR(0, VKZLIB_PP_CAT(_VKZLIB_PP_SIGNATURE_IS_VOLATILE_IMPL_TRUE_, X))
#define _VKZLIB_PP_SIGNATURE_IS_CONST_VOLATILE_IMPL_TRUE_ConstVolatile VKZLIB_PP_CONST(1)
#define VKZLIB_PP_SIGNATURE_IS_CONST_VOLATILE(X) \
	VKZLIB_PP_PICK_SECOND_OR(0, VKZLIB_PP_CAT(_VKZLIB_PP_SIGNATURE_IS_CONST_VOLATILE_IMPL_TRUE_, X))

#define _VKZLIB_PP_SIGNATURE_IS_LVALUE_IMPL_TRUE_LValue VKZLIB_PP_CONST(1)
#define VKZLIB_PP_SIGNATURE_IS_LVALUE(X) \
	VKZLIB_PP_PICK_SECOND_OR(0, VKZLIB_PP_CAT(_VKZLIB_PP_SIGNATURE_IS_LVALUE_IMPL_TRUE_, X))
#define _VKZLIB_PP_SIGNATURE_IS_RVALUE_IMPL_TRUE_RValue VKZLIB_PP_CONST(1)
#define VKZLIB_PP_SIGNATURE_IS_RVALUE(X) \
	VKZLIB_PP_PICK_SECOND_OR(0, VKZLIB_PP_CAT(_VKZLIB_PP_SIGNATURE_IS_RVALUE_IMPL_TRUE_, X))

#define _VKZLIB_PP_SIGNATURE_IS_NOEXCEPT_IMPL_TRUE_Noexcept VKZLIB_PP_CONST(1)
#define VKZLIB_PP_SIGNATURE_IS_NOEXCEPT(X) \
	VKZLIB_PP_PICK_SECOND_OR(0, VKZLIB_PP_CAT(_VKZLIB_PP_SIGNATURE_IS_NOEXCEPT_IMPL_TRUE_, X))

#endif // VKZLIB_MPL_PREPROCESSOR_SIGNATURE_IS_TAG_HPP