#ifndef VKZLIB_MPL_PREPROCESSOR_CAT_HPP
#define VKZLIB_MPL_PREPROCESSOR_CAT_HPP

#define _VKZLIB_PP_CAT_IMPL(X, Y) X##Y
/**
 * @brief Concatenate two tokens (So that no whitespace is needed to separate them)
 */
#define VKZLIB_PP_CAT(X, Y) _VKZLIB_PP_CAT_IMPL(X, Y)
#define VKZLIB_PP_CAT3_RIGHT(X1, X2, X3) VKZLIB_PP_CAT(X1, VKZLIB_PP_CAT(X2, X3))
#define VKZLIB_PP_CAT4_RIGHT(X1, X2, X3, X4) VKZLIB_PP_CAT(X1, VKZLIB_PP_CAT3_RIGHT(X2, X3, X4))
#define VKZLIB_PP_CAT3_LEFT(X1, X2, X3) VKZLIB_PP_CAT(VKZLIB_PP_CAT(X1, X2), X3)
#define VKZLIB_PP_CAT4_LEFT(X1, X2, X3, X4) VKZLIB_PP_CAT(VKZLIB_PP_CAT3_LEFT(X1, X2, X3), X4)

#endif // VKZLIB_MPL_PREPROCESSOR_CAT_HPP