#ifndef VKZLIB_MPL_PREPROCESSOR_CONDITIONAL_HPP
#define VKZLIB_MPL_PREPROCESSOR_CONDITIONAL_HPP

#include <vkzlib/mpl/preprocessor/cat.hpp>
#include <vkzlib/mpl/preprocessor/is_zero.hpp>
#include <vkzlib/mpl/preprocessor/unpack_tuple.hpp>

#define _VKZLIB_PP_CONDITIONAL_TUPLE_IMPL_0(TRUE_TUPLE, FALSE_TUPLE) VKZLIB_PP_UNPACK_TUPLE TRUE_TUPLE
#define _VKZLIB_PP_CONDITIONAL_TUPLE_IMPL_1(TRUE_TUPLE, FALSE_TUPLE) VKZLIB_PP_UNPACK_TUPLE FALSE_TUPLE
#define VKZLIB_PP_CONDITIONAL_TUPLE(CONDITION, TRUE_TUPLE, FALSE_TUPLE) \
	VKZLIB_PP_CAT(_VKZLIB_PP_CONDITIONAL_TUPLE_IMPL_, VKZLIB_PP_IS_ZERO(CONDITION)) (TRUE_TUPLE, FALSE_TUPLE)

#define VKZLIB_PP_CONDITIONAL(CONDITION, TRUE_TOKEN, FALSE_TOKEN) \
	VKZLIB_PP_CONDITIONAL_TUPLE(CONDITION, (TRUE_TOKEN), (FALSE_TOKEN))

#endif // VKZLIB_MPL_PREPROCESSOR_CONDITIONAL_HPP