#ifndef VKZLIB_MPL_PREPROCESSOR_EMPTY_TUPLE_HPP
#define VKZLIB_MPL_PREPROCESSOR_EMPTY_TUPLE_HPP

/**
 * @brief Empty tuple
 */
#define VKZLIB_PP_EMPTY_TUPLE() ()

#endif // VKZLIB_MPL_PREPROCESSOR_EMPTY_TUPLE_HPP