#ifndef VKZLIB_MPL_PREPROCESSOR_EXPAND_IF_HPP
#define VKZLIB_MPL_PREPROCESSOR_EXPAND_IF_HPP

#include <vkzlib/mpl/preprocessor/conditional.hpp>
#include <vkzlib/mpl/preprocessor/empty_tuple.hpp>

#define VKZLIB_PP_EXPAND_TUPLE_IF(CONDITION, TUPLE) \
	VKZLIB_PP_CONDITIONAL_TUPLE(CONDITION, TUPLE, VKZLIB_PP_EMPTY_TUPLE())

#define VKZLIB_PP_EXPAND_IF(CONDITION, TOKEN) \
	VKZLIB_PP_EXPAND_TUPLE_IF(CONDITION, (TOKEN))

#endif // VKZLIB_MPL_PREPROCESSOR_EXPAND_IF_HPP